#Task 1 — Load, Inspect, and Clean

In [56]:
import pandas as pd
url = "/content/used_cars_messy[1].csv"
df = pd.read_csv(url)
df.shape

(15661, 14)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB

In [58]:
df.isnull().sum() * 100 / len(df)

Unnamed: 0            0.000000
car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

In [59]:
df=df.dropna(subset=["selling_price"])

In [60]:
df["mileage"]=df["mileage"].str.strip().str.replace("km","").str.replace("kms","").str.replace(",","")
df["mileage"]=pd.to_numeric(df["mileage"],errors='coerce')
df["mileage"]=df["mileage"].fillna(df["mileage"].median())
df.isna().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage                 0
engine               1852
max_power             791
seats                 438
selling_price           0
dtype: int64

In [61]:
cols=["engine","max_power"]
for i in cols:
  df[i]=df[i].fillna(df[i].median())

In [62]:
df["km_driven"]=df["km_driven"].str.strip().str.replace("kms","").str.replace(",","").str.replace("km","")
df["km_driven"]=pd.to_numeric(df["km_driven"])

In [63]:
df=df.drop(columns=["Unnamed: 0","car_name","model"])
df

,brand,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda,3,48959,Dealer,Petrol,Manual,19.67,1497.0,117.60,5.0,875000.0
3,Mahindra,6,82000,dealer,Diesel,Manual,15.40,2179.0,88.50,8.0,925000.0
4,Mahindra,4,34000,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,Volkswagen,11,59000,Dealer,Petrol,Manual,16.09,1248.0,103.20,5.0,249000.0
15658,Maruti,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,Hyundai,2,15000,Dealer,Petrol,Manual,18.60,1197.0,81.86,5.0,620000.0
15660,Maruti,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [64]:
df["seats"]=df["seats"].fillna(df["seats"].mode()[0])

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              15503 non-null  object
 1   vehicle_age        15503 non-null  int64
 2   km_driven          15503 non-null  int64
 3   seller_type        15503 non-null  object
 4   fuel_type          15503 non-null  object
 5   transmission_type  15503 non-null  object
 6   mileage            15503 non-null  float64
 7   engine             15503 non-null  float64
 8   max_power          15503 non-null  float64
 9   seats              15503 non-null  float64
 10  selling_price      15503 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.4+ MB

In [66]:
df=df.drop_duplicates()

In [67]:
df["seller_type"].unique()

array(['Dealer', 'dealer', 'Individual', 'individual', 'DEALER',
       'Trustmark Dealer', 'Individul', 'Individuall', 'Delaer'],
      dtype=object)

In [68]:
df["seller_type"]=df["seller_type"].str.strip().str.title().str.replace("Individul","Individual").str.replace("Individuall","Individual").str.replace("Delaer","Dealer")

/tmp/ipykernel_585/516840023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["seller_type"]=df["seller_type"].str.strip().str.title().str.replace("Individul","Individual").str.replace("Individuall","Individual").str.replace("Delaer","Dealer")

In [69]:
df["seller_type"].unique()

array(['Dealer', 'Individual', 'Trustmark Dealer'], dtype=object)

In [70]:
df["fuel_type"].unique()

array(['Diesel', 'CNG', 'Petrol', 'Petrol ', 'DIESEL', ' Petrol',
       'petrol ', 'PETROL', ' Diesel', 'diesel ', 'LPG', 'petrol',
       'diesel', 'Electric'], dtype=object)

In [71]:
df["fuel_type"]=df["fuel_type"].str.strip().str.title()

/tmp/ipykernel_585/569078367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["fuel_type"]=df["fuel_type"].str.strip().str.title()

In [72]:
df["fuel_type"].unique()

array(['Diesel', 'Cng', 'Petrol', 'Lpg', 'Electric'], dtype=object)

In [73]:
df.shape

(15245, 11)

#Task 2 — Encode Categorical Features

In [74]:
df["transmission_type"]=df["transmission_type"].map({"Manual":0,"Automatic":1})
df

/tmp/ipykernel_585/3612484896.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["transmission_type"]=df["transmission_type"].map({"Manual":0,"Automatic":1})

,brand,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault,7,67647,Dealer,Diesel,0,19.87,1461.0,83.80,5.0,575000.0
1,Maruti,3,52000,Dealer,Cng,0,33.54,998.0,67.04,5.0,435000.0
2,Honda,3,48959,Dealer,Petrol,0,19.67,1497.0,117.60,5.0,875000.0
3,Mahindra,6,82000,Dealer,Diesel,0,15.40,2179.0,88.50,8.0,925000.0
4,Mahindra,4,34000,Dealer,Diesel,1,16.00,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti,7,127731,Dealer,Diesel,0,20.77,1248.0,88.80,7.0,665000.0
15657,Volkswagen,11,59000,Dealer,Petrol,0,16.09,1248.0,103.20,5.0,249000.0
15658,Maruti,7,20000,Individual,Petrol,0,20.51,998.0,67.04,5.0,250000.0
15659,Hyundai,2,15000,Dealer,Petrol,0,18.60,1197.0,81.86,5.0,620000.0
15660,Maruti,2,30000,Individual,Petrol,1,20.28,1462.0,103.25,5.0,960000.0

In [75]:
df=pd.get_dummies(df,columns=["fuel_type","seller_type"],drop_first=True)
df

,brand,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,selling_price,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,seller_type_Individual,seller_type_Trustmark Dealer
0,Renault,7,67647,0,19.87,1461.0,83.80,5.0,575000.0,True,False,False,False,False,False
1,Maruti,3,52000,0,33.54,998.0,67.04,5.0,435000.0,False,False,False,False,False,False
2,Honda,3,48959,0,19.67,1497.0,117.60,5.0,875000.0,False,False,False,True,False,False
3,Mahindra,6,82000,0,15.40,2179.0,88.50,8.0,925000.0,True,False,False,False,False,False
4,Mahindra,4,34000,1,16.00,2179.0,140.00,7.0,1175000.0,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti,7,127731,0,20.77,1248.0,88.80,7.0,665000.0,True,False,False,False,False,False
15657,Volkswagen,11,59000,0,16.09,1248.0,103.20,5.0,249000.0,False,False,False,True,False,False
15658,Maruti,7,20000,0,20.51,998.0,67.04,5.0,250000.0,False,False,False,True,True,False
15659,Hyundai,2,15000,0,18.60,1197.0,81.86,5.0,620000.0,False,False,False,True,False,False
15660,Maruti,2,30000,1,20.28,1462.0,103.25,5.0,960000.0,False,False,False,True,True,False

In [76]:
df.shape

(15245, 15)

In [77]:
df.columns.tolist()

['brand',
 'vehicle_age',
 'km_driven',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price',
 'fuel_type_Diesel',
 'fuel_type_Electric',
 'fuel_type_Lpg',
 'fuel_type_Petrol',
 'seller_type_Individual',
 'seller_type_Trustmark Dealer']

#Why drop_first=True is used:
Ans: In one-hot encoding, each category is converted into a separate binary column. Using drop_first=True removes one of these columns to avoid dummy variable trap (multicollinearity), where one column can be perfectly predicted from the others. This helps models (especially linear models) perform better and avoids redundant information.

#What a row of all zeros represents:

A row with all zeros in the dummy columns represents the dropped (reference) category. Since one category is removed, any instance that belongs to that category will have 0 in all the remaining dummy columns.

#Task 3 — Split and Compute Baseline MAE

In [78]:
x=df.drop(columns=["selling_price"])
y=df["selling_price"]

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [102]:
import numpy as np
mean_value = np.mean(y_train)
y_pred = np.full(len(y_test), mean_value)
mae = mean_absolute_error(y_test, y_pred)
print(f"Baseline MAE: ₹{round(mae)}")

Baseline MAE: ₹643628